#version: '3' version is depreciated
services:
  app:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

